With pydantic version >=1.8 on Windows the following error occured which was resolved by updating to the latest pydantic version: ImportError: cannot import name 'SettingsSourceCallable' from 'pydantic.env_settings'